name: Build and Push Docker Image

on:
  push:
    branches:
      - Uat
      - dev
      - prod

jobs:
  build-and-push:
    name: Build & Push Docker Image to AWS ECR
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{secrets.AWS_REGION}} 
      ECR_REPOSITORY: my-app
      IMAGE_TAG: latest12
      IMAGE_URI: 313616258649.dkr.ecr.us-east-1.amazonaws.com/app2

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
        aws-region: ${{secrets.AWS_REGION}} 

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        run: |
          IMAGE_TAG="${GITHUB_REF##*/}"  # Extracts the branch name
          echo "Building image for branch: $IMAGE_TAG"
          docker build -t $IMAGE_URI:$IMAGE_TAG .
          docker push $IMAGE_URI:$IMAGE_TAG
