name: Build and Push Docker Image

on:
  push:
    branches:
      - Uat
      - dev
      - prod

jobs:
  build-and-push:
    name: Build & Push Docker Image to AWS ECR
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }} 
      ECR_REPOSITORY: app2
      IMAGE_TAG: latest13
      IMAGE_URI: 313616258649.dkr.ecr.us-east-1.amazonaws.com/app2

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t my-app:${{ env.IMAGE_TAG }} .

      - name: Tag Docker image
        run: |
          docker tag my-app:${{ env.IMAGE_TAG }} ${{ env.IMAGE_URI }}

      - name: Push Docker image to ECR
        run: |
          docker push ${{ env.IMAGE_URI }}
